# Generated by Django 5.0.6 on 2026-02-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
